### PR TITLE
input range to count button, responsive

### PR DESCRIPTION
**Pull request by vadostuta**
i have some trouble with positioning first input value, so take a look.

### CODE REVIEW

**Comment by khutten** [comment]
Really appreciate you putting this PR up @vadikcorp, I'm a little busy right now, but I'll review this when I can.

**Comment by mrhut10** [comment]
thank you @vadikcorp 
the css-grid is limiting it to the sidebar.
capture

We need create a new area within our css-grid that sits below both sides. That being sad maybe our naming convention of those areas will need to be changed to address this restructure.

what timezone are you in @vadikcorp ?

**Comment by vadikcorp** [comment]
@mrhut10 GMT+3

**Comment by mrhut10** [comment]
cool I'm on GMT+10. but only available on this project in the evenings currently.
Tomorrow evening, I'll alter the CSS grid layout to better suit what we are doing here :)

**Comment by vadikcorp** [comment]
okay, tip me:) do u have some communication chat or something like that?

**Comment by mrhut10** [comment]
@vadikcorp are you able to have a look at this to see if you can make your changes updated to work with master branch?

if you have any trouble i can likely jump in and have a look in the middle of the night.

**Pull request closed without merging**
